apiVersion: v1
kind: Service
metadata:
  name: milvus-cdc-service
  labels:
    app: milvus-cdc
    instance: my-release
spec:
  selector:
    app: milvus-cdc
    instance: my-release
  ports:
  - name: milvus-cdc
    protocol: TCP
    port: 8444
    targetPort: 8444