---
address: 0.0.0.0
port: 8444
task.maxNum: 100
name:maxLength: 256
etcd:
  endpoints:
    - 10.101.66.176:2379
  rootpath: cdc_16_38
source:
  etcd:
    endpoints:
      - 10.101.66.176:2379
    rootpath: by-dev # etcd rootpath
    meta:
      path: meta # etcd meta sub path
  defaultPartitionName: _default
  reader.buffer.len: 10
  mqtype: pulsar
  pulsar:
    address: 10.101.139.150
    port: 6650
    web.address:
    web.port: 80
    max.message.size: 5242880
    tenant: public
    namespace: default
  kafka:
    broker_list: 127.0.0.1:9092
    
